CREATE DATABASE `predictions` /*!40100 DEFAULT CHARACTER SET latin1 */;
CREATE TABLE `predictions`.`mfcc_feature` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `RecordingID` tinytext NOT NULL,
  `FrameOffset` int(11) NOT NULL,
  `MfccCoefficient0` float NOT NULL,
  `MfccCoefficient1` float NOT NULL,
  `MfccCoefficient2` float NOT NULL,
  `MfccCoefficient3` float NOT NULL,
  `MfccCoefficient4` float NOT NULL,
  `MfccCoefficient5` float NOT NULL,
  `MfccCoefficient6` float NOT NULL,
  `MfccCoefficient7` float NOT NULL,
  `MfccCoefficient8` float NOT NULL,
  `MfccCoefficient9` float NOT NULL,
  `MfccCoefficient10` float NOT NULL,
  `MfccCoefficient11` float NOT NULL,
  `MfccCoefficient12` float NOT NULL,
  `MfccDeltaCoefficient0` float NOT NULL,
  `MfccDeltaCoefficient1` float NOT NULL,
  `MfccDeltaCoefficient2` float NOT NULL,
  `MfccDeltaCoefficient3` float NOT NULL,
  `MfccDeltaCoefficient4` float NOT NULL,
  `MfccDeltaCoefficient5` float NOT NULL,
  `MfccDeltaCoefficient6` float NOT NULL,
  `MfccDeltaCoefficient7` float NOT NULL,
  `MfccDeltaCoefficient8` float NOT NULL,
  `MfccDeltaCoefficient9` float NOT NULL,
  `MfccDeltaCoefficient10` float NOT NULL,
  `MfccDeltaCoefficient11` float NOT NULL,
  `MfccDeltaCoefficient12` float NOT NULL,
  `MfccDeltaDeltaCoefficient0` float NOT NULL,
  `MfccDeltaDeltaCoefficient1` float NOT NULL,
  `MfccDeltaDeltaCoefficient2` float NOT NULL,
  `MfccDeltaDeltaCoefficient3` float NOT NULL,
  `MfccDeltaDeltaCoefficient4` float NOT NULL,
  `MfccDeltaDeltaCoefficient5` float NOT NULL,
  `MfccDeltaDeltaCoefficient6` float NOT NULL,
  `MfccDeltaDeltaCoefficient7` float NOT NULL,
  `MfccDeltaDeltaCoefficient8` float NOT NULL,
  `MfccDeltaDeltaCoefficient9` float NOT NULL,
  `MfccDeltaDeltaCoefficient10` float NOT NULL,
  `MfccDeltaDeltaCoefficient11` float NOT NULL,
  `MfccDeltaDeltaCoefficient12` float NOT NULL,
  `ArousalPrediction` float NOT NULL,
  `ValencePrediction` float NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=444 DEFAULT CHARSET=latin1;
CREATE DATABASE `predictormanager` /*!40100 DEFAULT CHARACTER SET latin1 */;
CREATE TABLE `predictormanager`.`predictor` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `predictorName` varchar(50) NOT NULL,
  `arousalPredictorFilename` varchar(250) NOT NULL,
  `valencePredictorFilename` varchar(250) NOT NULL,
  `principalComponentTransformerFilename` varchar(250) NOT NULL,
  `active` tinyint(1) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `predictorName` (`predictorName`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=latin1;