from datetime import datetime
from predictormanager import db
 
class Predictor( db.Model ):
    __table_args__ = { 'schema': 'predictormanager' }
    id = db.Column( db.Integer, primary_key = True )
    predictorName = db.Column( db.String( 50 ), unique = True, nullable = False )
    arousalPredictorFilename = db.Column( db.String( 250 ), nullable = False )
    valencePredictorFilename = db.Column( db.String( 250 ), nullable = False )
    principalComponentTransformerFilename = db.Column( db.String( 250 ), nullable = False )
    active = db.Column( db.Boolean(), nullable = False )
    def __repr__( self ):
        return "Predictor('{}, {}, {}, {}')".format( self.predictorName, self.arousalPredictorFilename, self.valencePredictorFilename, self.active )

class MfccFeature( db.Model ):
    __table_args__ = { 'schema': 'predictions' }
    ID = db.Column( db.Integer, primary_key = True )
    RecordingID = db.Column( db.String( 32 ), nullable = False )
    FrameOffset = db.Column( db.Integer, nullable = False )
    MfccCoefficient0 = db.Column( db.Float, nullable = False )
    MfccCoefficient1 = db.Column( db.Float, nullable = False )
    MfccCoefficient2 = db.Column( db.Float, nullable = False )
    MfccCoefficient3 = db.Column( db.Float, nullable = False )
    MfccCoefficient4 = db.Column( db.Float, nullable = False )
    MfccCoefficient5 = db.Column( db.Float, nullable = False )
    MfccCoefficient6 = db.Column( db.Float, nullable = False )
    MfccCoefficient7 = db.Column( db.Float, nullable = False )
    MfccCoefficient8 = db.Column( db.Float, nullable = False )
    MfccCoefficient9 = db.Column( db.Float, nullable = False )
    MfccCoefficient10 = db.Column( db.Float, nullable = False )
    MfccCoefficient11 = db.Column( db.Float, nullable = False )
    MfccCoefficient12 = db.Column( db.Float, nullable = False )
    MfccDeltaCoefficient0 = db.Column( db.Float, nullable = False )
    MfccDeltaCoefficient1 = db.Column( db.Float, nullable = False )
    MfccDeltaCoefficient2 = db.Column( db.Float, nullable = False )
    MfccDeltaCoefficient3 = db.Column( db.Float, nullable = False )
    MfccDeltaCoefficient4 = db.Column( db.Float, nullable = False )
    MfccDeltaCoefficient5 = db.Column( db.Float, nullable = False )
    MfccDeltaCoefficient6 = db.Column( db.Float, nullable = False )
    MfccDeltaCoefficient7 = db.Column( db.Float, nullable = False )
    MfccDeltaCoefficient8 = db.Column( db.Float, nullable = False )
    MfccDeltaCoefficient9 = db.Column( db.Float, nullable = False )
    MfccDeltaCoefficient10 = db.Column( db.Float, nullable = False )
    MfccDeltaCoefficient11 = db.Column( db.Float, nullable = False )
    MfccDeltaCoefficient12 = db.Column( db.Float, nullable = False )
    MfccDeltaDeltaCoefficient0 = db.Column( db.Float, nullable = False )
    MfccDeltaDeltaCoefficient1 = db.Column( db.Float, nullable = False )
    MfccDeltaDeltaCoefficient2 = db.Column( db.Float, nullable = False )
    MfccDeltaDeltaCoefficient3 = db.Column( db.Float, nullable = False )
    MfccDeltaDeltaCoefficient4 = db.Column( db.Float, nullable = False )
    MfccDeltaDeltaCoefficient5 = db.Column( db.Float, nullable = False )
    MfccDeltaDeltaCoefficient6 = db.Column( db.Float, nullable = False )
    MfccDeltaDeltaCoefficient7 = db.Column( db.Float, nullable = False )
    MfccDeltaDeltaCoefficient8 = db.Column( db.Float, nullable = False )
    MfccDeltaDeltaCoefficient9 = db.Column( db.Float, nullable = False )
    MfccDeltaDeltaCoefficient10 = db.Column( db.Float, nullable = False )
    MfccDeltaDeltaCoefficient11 = db.Column( db.Float, nullable = False )
    MfccDeltaDeltaCoefficient12 = db.Column( db.Float, nullable = False )
    ArousalPrediction = db.Column( db.Float, nullable = False )
    ValencePrediction = db.Column( db.Float, nullable = False )
